chainguard-dev/terraform-infra-common

cloudevent-recorder/recorder.tf
I hit this trying to bring my dev environment back up with the new hotness.
=> Fix bad iterator variable in recorder.

.github/workflows/documentation.yaml, cloudevent-broker/README.md, cloudevent-broker/ingress.tf, cloudevent-recorder/README.md, cloudevent-recorder/recorder.tf, otel-collector/README.md, otel-collector/cmd/otel-collector/kodata/config.yaml, otel-collector/cmd/otel-collector/main.go, otel-collector/main.tf, otel-collector/outputs.tf, otel-collector/variables.tf
This produces the image and grants the service account as which it will run permission to publish metrics.
=> Add an `otel-collector` module

dashboard/sections/grpc/grpc.tf
Outbound gRPC dashboards do not work yet.
=> Remove extraneous modules

dashboard/sections/grpc/grpc.tf, dashboard/service/README.md, dashboard/service/dashboard.tf, dashboard/service/variables.tf
This makes use of what we added in #42
=> Add gRPC outbounds, remove grpc_service_name

regional-go-service/main.tf
Fixes: https://github.com/chainguard-dev/terraform-cloudrun-glue/issues/46
=> Add a `depends_on` to public IAM logic.

.github/dependabot.yml, .github/workflows/style.yaml, go.mod, modules/regional-go-service/main.tf
- group dependabot updates
- update golangci-lint
- update go version in go.mod
- update check for public-services-are-unauthenticated resource
=> some updates

modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/dashboard/service/variables.tf
Only the key-space / size of a map needs to be known at plan time, so this should be safe to for_each 🤞
=> Change the type of dashboard var.alerts

modules/otel-collector/cmd/otel-collector/kodata/config.yaml
Reverts chainguard-dev/terraform-infra-common#102
=> Revert "Tune otel collector GMP exporter settings"

modules/prober/README.md, modules/prober/alert.tf, modules/prober/gclb.tf, modules/prober/main.tf, modules/prober/outputs.tf, modules/prober/variables.tf, pkg/prober/prober.go
It also adapts that code to support using the primitives from here.
=> This moves terraform-google-prober into this repository.

modules/dashboard/cloudevent-receiver/dashboard.tf
Plumb through missing `subscription_prefix`
=> Add missing parameter.

modules/cloudevent-broker/ingress.tf, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/job/dashboard.tf, modules/dashboard/sections/resources/main.tf, modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/dashboard/service/variables.tf
applied here, [link](https://console.cloud.google.com/monitoring/dashboards/builder/f7a35b30-7561-4fbf-bbe3-500d9c9dab52;duration=P1D?project=kleung-chainguard&supportedpurview=project&f.rlabel.service_name=enforce-registry)
=> add alert for oom for services

modules/cloudevent-recorder/recorder.tf, modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/cloudevent-receiver/variables.tf
matches that of service dashboard
=> add error reporting to cloudevent receiver

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/bigquery.tf, modules/cloudevent-recorder/recorder.tf, modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/variables.tf
fix: https://github.com/chainguard-dev/terraform-infra-common/issues/117
=> bigquery dts alert, successful run within 30min

pkg/httpmetrics/transport.go
https://github.com/chainguard-dev/terraform-infra-common/pull/137 but for outgoing latencies
=> more outgoing http latency buckets

modules/regional-go-service/README.md, modules/regional-go-service/main.tf, modules/secret/README.md, modules/secret/main.tf
Fixes: https://github.com/chainguard-dev/terraform-infra-common/issues/147
=> Add a Cloud Run alert policy.

modules/cron/main.tf, modules/regional-go-service/main.tf
This will still alert if there is a deletion, but I think that's OK.
=> Don't alert on creations

modules/dashboard/sections/github/main.tf, pkg/httpmetrics/transport.go
=> improve github rate limit API metrics and dashboard

modules/audit-serviceaccount/main.tf, modules/cloudevent-recorder/main.tf, modules/configmap/main.tf, modules/cron/main.tf, modules/regional-go-service/main.tf, modules/secret/main.tf
switched from subject to email, as subject sometimes is not populated
=> extract email for all abnormal access alerts

modules/secret/README.md, modules/secret/main.tf, modules/secret/variables.tf
=> feature: optional creation of dummy secret version to avoid bad reference on first deploy

modules/github-events/schemas/event_types.go, modules/github-events/schemas/pull_request.schema.json, modules/github-events/schemas/workflow_run.schema.json
Currently we're missing some fields when converting to our schema type. These changes capture all fields
=> Update event types for workflow run

modules/cron/README.md, modules/cron/main.tf, modules/cron/outputs.tf, modules/cron/variables.tf, modules/regional-go-service/README.md, modules/regional-go-service/outputs.tf
also add output of names of services/jobs.
=> add option to declare invokers for cloud run jobs

modules/cron/README.md, modules/cron/main.tf
the iam_members resource were overwritten by the iam_bindings for invoker
append the user invokers to iam bindings.
=> fix: append invoker to bindings 

modules/audit-serviceaccount/main.tf, modules/cloudevent-recorder/main.tf, modules/configmap/main.tf, modules/cron/main.tf, modules/regional-go-service/main.tf, modules/secret/main.tf, modules/serverless-gclb/main.tf
make it easier to identify what action and user of the triggered violation
the current alert isnt clear on what action actually triggered the alert, and how
user agent can show if it was terraform
and method can show what specific action
=> alerting: include method and user agent for triggered alert

pkg/octosts/octosts.go
This should make local development easier if less secure.
Either:
```
GITHUB_TOKEN=$(gh auth token) go run ./cmd/blah
```
or
```
chainctl auth octosts -- go run ./cmd/blah
```
...which will generate an Octo STS token, run the command and then revoke the token when the command exits.
=> octosts: optionally use GH token for local dev

modules/cloudevent-recorder/recorder.tf
seeing oom now that it is serving metrics
=> infra: increase memory from 256M to 1.5G

modules/cron/README.md, modules/cron/main.tf, modules/cron/variables.tf
this is to support passing in groups and not just users for invokers.
=> fix: change invokers to be list of iam members and not emails

modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go, modules/github-events/cmd/schemagen/main.go, modules/github-events/main.tf, modules/github-events/schemas/event_types.go, modules/github-events/schemas/issue_comment.schema.json
add `IssueComment*` and the appropriate schema/handlers
=> add issue comment schema

modules/cron/README.md, modules/cron/main.tf
context: https://chainguard-dev.slack.com/archives/D04UX0QCQDS/p1714149558515299
=> fix permissions to allow invoker to list job to access it.

modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/variables.tf, modules/dashboard/sections/resources/README.md, modules/dashboard/sections/resources/main.tf
motivation, disable oom policy for sbom-ingester and vuln-ingester
known issue and unlikely to be fixed
they are noisy in the UI, not alerting, but the alert page is spammed with it
=> feature: toggle to enable/disable oom policy

modules/dashboard/sections/gorm/README.md, modules/dashboard/sections/gorm/gorm.tf, modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/dashboard/service/variables.tf
plan is to enable gorm section for datastore services.
will update playbooks once this is rolled out for datastore
=> add gorm section to service dashboard, defaulted off

modules/cron/README.md, modules/cron/main.tf, modules/cron/variables.tf
for https://github.com/chainguard-dev/mono/issues/17439
=> optional success alert for cron job

modules/github-bots/sdk/github.go
When the octo-sts policy was incorrect we ran into two errors.
The first one in `handleGithubResponse` was a cryptic segfault where `resp` was nil so accessing `resp.Response` threw an error
The second was in the `Close()` function we check if `ts.tok` is nil before trying to revoke. Previously it was never nil, it was an pointer to a Token struct with an empty token. This caused us to fail on token revocation
=> github-bots handle token error

modules/github-events/main.tf
Forgot to add this when I created the schema.json
=> Add issue schema to github-events output

modules/alerting/main.tf, modules/alerting/variables.tf
=> alert for cloud run server failure rate

modules/github-events/README.md, modules/github-events/main.tf
I broke staging today so I'm leaving this warning and a playbook so hopefully I don't do it again
=> Add a warning for recorder deletion_protection

modules/cloudevent-recorder/cmd/logrotate/main.go, pkg/rotate/blob.go
Also notify context on SIGTERM
=> logrotate to delete files incrementally

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/recorder.tf, modules/cloudevent-recorder/variables.tf
will attempt to set flush interval to 1m in staging to see if that would help with the oom'ing issue
theory is that there is a backlog of files causing the oom'ing
if we flush more frequently, it should avoid build up of files.
=> allow flush interval to be configurable for recorder

pkg/rotate/blob.go
convert logging to use clog
add logging for how may files found needing to be processed
=> add more logging for rotate

modules/alerting/README.md, modules/cron/example/README.md, modules/dashboard/sections/github/README.md, modules/dashboard/sections/resources/README.md, modules/dashboard/sections/subscription/README.md, modules/serverless-gclb/README.md, modules/serverless-gclb/main.tf, modules/serverless-gclb/variables.tf
=> Add optional IAP support to Cloud Run services.

modules/alerting/main.tf
=> fix null service in notification for 5xx ratio

modules/alerting/main.tf
this page will replace the absolute 5xx count page in mono
=> change 5xx ratio failure to page

modules/regional-go-service/README.md, modules/regional-go-service/outputs.tf, modules/regional-service/README.md, modules/regional-service/outputs.tf
output uri such that it can be referenced 
same for locations
=> output more cloudrun service properties

pkg/httpmetrics/metrics.go
We worked around CR trace issue, so stop sampling at 100%.
=> Stop sampling at 100% 

modules/cloudevent-trigger/README.md
i was looking at the example to understand how that works and i think that was wrong, so update to what i think is the correct one
=> fix example for cloudevent-trigger

modules/dashboard/sections/subscription/main.tf
=> Fix typo in #399

modules/alerting/README.md, modules/alerting/main.tf
eventing failure rate does not justify being pageable
have it routed to slack only
=> handle eventing failure rate separately

modules/alerting/README.md, modules/alerting/main.tf
add log based metrics to track frequency over time
=> tune spammy alerts to only alert once a day

modules/cron/README.md, modules/cron/main.tf
mirrors that of regional service
https://github.com/chainguard-dev/terraform-infra-common/blob/main/modules/regional-service/main.tf#L1-L17
=> grant service account telemetry permissions for cron job service account

modules/cron/README.md, modules/cron/main.tf, modules/cron/variables.tf
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job#body
https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.jobs/run#request-body
=> allow overrides for scheduled cron job

modules/networking/main.tf
for https://github.com/chainguard-dev/internal/issues/3615
=> enable vpc flow log for network module

go.mod, go.sum
Picks up https://github.com/chainguard-dev/clog/pull/21
=> deps: bump clog to @main

go.mod, go.sum, modules/bucket-events/cmd/trampoline/main.go, modules/cloudevent-broker/cmd/ingress/main.go, modules/cloudevent-recorder/cmd/dejavu-bq/main.go, modules/cloudevent-recorder/cmd/logrotate/main.go, modules/cloudevent-recorder/cmd/recorder/main.go, modules/github-bots/sdk/bot.go, modules/github-events/cmd/trampoline/main.go, pkg/httpmetrics/metrics.go, pkg/profiler/profiler.go
=> fix envconfig structs, bump clog to release

modules/github-bots/sdk/github.go
Since we are doing our own token reuse and revocation, the wrapping done by oauth2.NewClient doesn't work, since it reuses tokens until they expire. Our tokens don't set an expiry, so they never expire.
=> github: Avoid redundant token reuse wrapper

modules/serverless-gclb/README.md, modules/serverless-gclb/main.tf
This reverts commit 4430f827fe7fa0fc39fd176a430993bdbdf7aa1f.
no longer needed
=> Revert "pin google provider to less than 6 (#518)"

modules/serverless-gclb/README.md, modules/serverless-gclb/main.tf
This reverts commit d49dacbe910acd91713bbde670dc25bd98506992.
actually needed for now
=> Reapply "pin google provider to less than 6 (#518)" (#537)

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
sample results; https://cloudlogging.app.goo.gl/JXgaXq1Lb6mjzwWR9
=> alert for timed out requests

modules/bucket-events/README.md, modules/bucket-events/dashboard.tf, modules/cloudevent-broker/README.md, modules/cloudevent-broker/ingress.tf, modules/dashboard/alerts/README.md, modules/dashboard/alerts/dashboard.tf, modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/job/README.md, modules/dashboard/job/dashboard.tf, modules/dashboard/json/README.md, modules/dashboard/json/main.tf, modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/github-bots/main.tf, modules/github-events/README.md, modules/github-events/dashboard.tf, modules/workqueue/README.md, modules/workqueue/dashboard.tf, modules/workqueue/dispatcher.tf, modules/workqueue/main.tf, modules/workqueue/outputs.tf
for https://github.com/chainguard-dev/internal-dev/issues/1617
this should allow us to re-enable comments with terraform diffs
=> Add new dashboard module that removes defaulted values that generates no-op diffs

modules/alerting/main.tf
It bothers me that log-based alerts don't include a link to the logs that triggered the alert, so this is an attempt to do that.
Based on some experimentation, I believe the general form of a Logs Explorer link is this:
https://console.cloud.google.com/logs/query;query=<query>?project=<project>
=> alerts: include documentation and links in alert

modules/bucket-events/README.md, modules/bucket-events/main.tf, modules/bucket-events/variables.tf, modules/cloudevent-broker/README.md, modules/cloudevent-broker/ingress.tf, modules/cloudevent-broker/variables.tf, modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/recorder.tf, modules/cloudevent-recorder/variables.tf, modules/github-events/README.md, modules/github-events/main.tf, modules/github-events/variables.tf, modules/prober/README.md, modules/prober/main.tf, modules/prober/variables.tf, modules/workqueue/README.md, modules/workqueue/dispatcher.tf, modules/workqueue/receiver.tf, modules/workqueue/variables.tf
for https://github.com/chainguard-dev/internal-dev/issues/4884
=> make squad not required for core infra modules

modules/regional-service/main.tf, modules/regional-service/otel-config/config.yaml
for https://github.com/chainguard-dev/internal-dev/issues/4886
=> insert squad label to all metrics

modules/alerting/main.tf
include squad name or "global" in alert policy name
fix promql policy to filter on new "team" label.
dead letter is global, do not create squad variant.
for https://github.com/chainguard-dev/internal-dev/issues/4886
=> fix name and promql squad policy

modules/alerting/README.md, modules/alerting/main.tf
this will trigger on every release (update service)
=> add alert for when a service is updated, but traffic is not routed to latest revision

modules/github-bots/sdk/github.go, modules/github-bots/sdk/github_integration_test.go
I want to search for the content in proposed filenames in a repository.
=> github-bot sdk: add search content of filename in repository

modules/bucket-events/main.tf, modules/cloudevent-recorder/recorder.tf, modules/cloudevent-recorder/subscriber-gcs.tf, modules/cloudevent-trigger/README.md, modules/cloudevent-trigger/main.tf, modules/cloudevent-trigger/variables.tf, modules/github-bots/main.tf
this would enable routing dlq alerts to the appropriate team
=> add team/squad labels to dlq topic

modules/github-bots/sdk/github.go, modules/github-bots/sdk/github_test.go
related to this thread in slack: https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1738862337902599
=> fix: panic with inner client

modules/alerting/main.tf
- exclude 503 from existing 5xx alert
- create new alert for 503
- page on non-503 5xx
- slack on 503
=> separate 503 from 5xx alert into its own alert

modules/github-bots/sdk/github.go
These were just using a context.Background() which meant they never got cancelled, which is not great. We might want to retry these when they fail, but we shouldn't hang forever if they do.
=> github: Add arbitrary 1 minute timeout to octosts

pkg/httpmetrics/metrics.go
This is getting called every new Handler(), which sends an HTTP request, which is likely to succeed quickly every time in cloud run, but might possibly fail sometimes. This is a little wasteful because we don't expect the result to ever change, so Once() it.
=> httpmetrics: Call oidc.NewProvider() once

modules/alerting/main.tf
name is `name : monitoring.regex.full_match(.*-dlq-.*)`
topic is `topic_id : enforce-staging-ing-sbom-dlq-92yg`
=> use better id for pubsub alert.

modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go
GitHub Issues https://docs.github.com/en/webhooks/webhook-events-and-payloads#issues
=> github-events: handle GitHub Issues event types

modules/cloudevent-pull-trigger/README.md, modules/cloudevent-pull-trigger/main.tf, modules/cloudevent-pull-trigger/outputs.tf, modules/cloudevent-pull-trigger/variables.tf
Create the abstractions for creating a Trigger that does not push events, but rather makes them available for pulling via a PubSub subscription.
=> feat: Add pull trigger abstraction to mirror push trigger.

modules/cloudevent-broker/README.md, modules/regional-go-service/README.md, modules/regional-service/README.md
Prompts
> Audit the examples in the readmes of each module and identify ones which are missing required variables
> Update the examples that are missing notification_channels to include passing an empty list with a comment to pass any relavent notification channels there.
=> Audit examples for required variables.

modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go
Add a new extension header to cloud events for pull request events in the format "pullrequest=org/repo#123". This enables downstream services to correlate events with specific pull requests.
The implementation extracts PR information from the webhook payload and includes unit tests for both the extraction function and the integration with cloud events.
=> github-events: Add pullrequest extension header to GitHub events

modules/github-bots/sdk/github.go
This allows callers to pass `shallow=true` to only do a shallow clone.
In order to make this change I had to add an optional options struct, which means existing callers will have to add `, nil` to the end off their callsite to get the current behavior. If they only want a shallow clone, add `&github.CloneOpts{Shallow: true}` instead.
=> breaking change: pass options to CloneRepo

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
for https://github.com/chainguard-dev/internal-dev/issues/12123
and other minor cleanups
=> grpc failure ratio alert

modules/gke/README.md, modules/gke/main.tf, modules/gke/variables.tf
this is to allow more detailed tracking usage in a gke cluster
=> make gke usage export configurable

pkg/rotate/blob.go
Currently, we're only retrying the respective `writer.Close` operation up to 3 times. However, retrying `Close` itself doesn't seem to be doing anything useful and just returns the same error over and over again.
Instead, this retries the entire operation. The a successful write operation consists of writing the respective blob **and** successfully calling `Close`. So in addition to the fixed retrying, this also moves deleting the respective files to **after** calling `Close` successfully, to ensure we're not losing state in error cases.
=> cloud-events-recorder: Fix behavior around retrying `writer.Close`

.github/chainguard/ghreconciler.sts.yaml
This is to let me experiment on a repo with more interesting CI checks.
=> Add a ghreconciler policy

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
xref: https://github.com/chainguard-dev/mono/pull/25067
=> replace pagerdutty with agnostic name for paging 

modules/alerting/main.tf
oom logging may be different
update filter
=> tune oom alert

pkg/workqueue/gcs/gcs.go
Currently, we compute the wait time based off of the created time. This means that if a key is re-attempted we are computing wait times off of the original time, which is not reflective of the actual queue wait time between attempts.
This changes to add a last-attempted timestamp when the object is re-enqueued, and modifying the metrics to compute off of this one if present, otherwise falling back to the original create time.
Unix timestamp used to minimize storage size.
=> workqueue: Store last attempted timestamp, compute wait metrics based on that time.

modules/regional-go-service/README.md, modules/regional-go-service/variables.tf, modules/regional-service/README.md, modules/regional-service/variables.tf
tested using gen2 on issuer for ~1 day
no issue. 
start defaulting to gen2
=> default to gen2 cloudrun

modules/cloudsql-postgres/main.tf
fixes https://github.com/chainguard-dev/internal-dev/issues/19682
=> postgres: set autoresize limit on replicas

modules/cron/README.md, modules/cron/variables.tf
=> enable otel side car for cloud run job by defaults

modules/alerting/main.tf, modules/cloudevent-recorder/bigquery.tf, modules/cron/main.tf, modules/dashboard/sections/subscription/main.tf, modules/prober/alert.tf, modules/secret/main.tf
first pass at setting severities
for https://github.com/chainguard-dev/internal-dev/issues/11206
=> set severity for alert policies

modules/azure-github-wif/README.md, modules/azure-github-wif/main.tf, modules/azure-github-wif/outputs.tf, modules/azure-github-wif/variables.tf
request https://github.com/chainguard-dev/mono/pull/27054#discussion_r2337038112
=> add azure github wif module

pkg/githubreconciler/reconciler.go
This should dramatically reduce the number of trust policies we need to enable automation across entire orgs.
=> Allow reconcilers to opt into org-scoped credentials.

modules/dashboard/sections/github/main.tf
added here: https://github.com/chainguard-dev/terraform-infra-common/pull/1146
=> Add the org to the github dashboard breakdown
