networking/README.md, networking/main.tf
This appears to be necessary to access Google services even with the bit set on the subnets.
=> Add a route to the internet gateway.

dashboard/job/README.md, dashboard/job/dashboard.tf, dashboard/sections/collapsible/main.tf, dashboard/sections/http/main.tf, dashboard/sections/layout/main.tf, dashboard/sections/logs/main.tf, dashboard/sections/resources/main.tf, dashboard/sections/width/main.tf, dashboard/service/README.md, dashboard/service/dashboard.tf, networking/README.md, networking/dns.tf
This layout is more cumbersome because of the requirement to explicitly lay things out, however, this change introduces a number of helper modules to make this a bit more tolerable.
At a high-level, "sections" (our own intermediate concept) produce groupings of tiles laid out relative to `(0, 0)` with a width of `module.width.size` (see below).
The modules in `./dashboard/sections` group our "widgets" into arrangements of "tiles" (e.g. logs, http, resources) with several special helper modules:
1. `width`: This module exists to define a global constant for the dashboard width,
1. `collapsible`: This wraps a list of tiles in a "collapsible" region with a title (it automagically figures out the bounding box, to avoid human error here),
1. `layout`: This takes a list of "sections" (defined …
=> Restructure the dashboards to leverage `mosaicLayout`

.github/workflows/documentation.yaml, cloudevent-broker/README.md, cloudevent-broker/ingress.tf, cloudevent-recorder/README.md, cloudevent-recorder/recorder.tf, dashboard/README.md, dashboard/cloudevent-receiver/README.md, dashboard/cloudevent-receiver/dashboard.tf, dashboard/cloudevent-receiver/variables.tf, dashboard/sections/subscription/main.tf, dashboard/sections/topic/main.tf
This creates sections for "topics" and "subscriptions" that filter on their respective prefixes.
The topic section shows both topic metrics and subscription metrics for topics matching the prefix. The subscription section shows the subscription metrics for subscriptions matching the prefix.
Building on this, the broker ingress now has a customized dashboard that takes advantage of the topic metrics to put them front-and-center. Also building on this, the event recorder now includes a section with subscription metrics for each even type.
=> Start to add eventing dashboards.

cloudevent-recorder/README.md, cloudevent-recorder/recorder.tf
The previous "fix" was still broken, but this cleanly applies with my local example changed to use the recorder.
=> Use the multi-variable `for` when walking a `map` type.

cloudevent-broker/cmd/ingress/main.go, cloudevent-broker/ingress.tf
Cloud Run services know what project they're running in, let's just use that.
=> cleanup: detect project ID instead of passing via env

dashboard/sections/alerts/main.tf, dashboard/sections/collapsible/main.tf, dashboard/service/README.md, dashboard/service/dashboard.tf, dashboard/service/variables.tf
This should produce full-width alert chart widgets for each alert. I might need to iterate on this with changes in tf-prober to see this all working together. It at least doesn't regress for non-alert-having services.
=> support passing alert IDs to service dashboards

dashboard/sections/alerts/main.tf, dashboard/service/README.md, dashboard/service/dashboard.tf, dashboard/service/variables.tf
This avoids the need to sprinkle `var.alert != ""` everywhere.
=> Make `alerts` a list and use a `for_each`.

dashboard/sections/http/main.tf, dashboard/service/dashboard.tf
This based on the metrics we export in our metricking transport.
There are some difference with Cloud Run native metrics:
1. we can't add `resource.type` to our metrics. I work around by not using `resource.type` in the filter here.
2. the cloud run native metrics has `service_name` being a `resource.label`, which AFAIK we can't add to our Prometheus metrics. when following the instruction [here](https://cloud.google.com/run/docs/tutorials/custom-metrics-opentelemetry-sidecar) the `service_name` is a `metric.label`. As a result, we will need to add that filter here, unlike the other widgets that can inherit from the Dashboard's. 
For 2. we could also add a template variable at the Dashboard level that use a `metric.label`, but will look a bit confusing as we have two drop downs that look …
=> Add outbound HTTP dashboard

dashboard/sections/grpc/grpc.tf, dashboard/service/README.md, dashboard/service/dashboard.tf, dashboard/service/variables.tf
Currently our gRPC metrics dp not have the right label `service_name` yet. That means we can't have outbound gRPC widgets (which would need to distinguish by caller i.e. `service_name`).
I'm using the `grpc_service_name` variable as a work around here. Will remove it and add outbound gRPC when the metric label is fixed.
=> Add gRPC (inbound)

otel-collector/cmd/otel-collector/kodata/config.yaml
The `gcp` resource detection plugin populates the attribute `faas.name` to Cloud Run Service/Job, and Cloud Function name, which makes it a nice way to standardize on naming ([see](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md)). Using env var is less convenient for this purpose because Cloud Run Service name is `$K_SERVICE` and for Cloud Run Job it's `$CLOUD_RUN_JOB`.
The googlemanagedprometheus exporter consumes `service.name` attribute and create a resource label named `job` with this value when uploading metrics. There is no customization of this. ([see](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/764)).
This PR plumbs `faas.name` into `service.name` so we can get a resource label …
=> otel-collector config to populate FAAS name

.github/workflows/documentation.yaml, cloudevent-broker/README.md, cloudevent-broker/ingress.tf, cloudevent-broker/outputs.tf, cloudevent-recorder/README.md, cloudevent-recorder/recorder.tf, cloudevent-trigger/README.md, dashboard/cloudevent-receiver/README.md, dashboard/service/README.md, otel-collector/README.md, regional-go-service/README.md, regional-go-service/main.tf, regional-go-service/variables.tf
This module encapsulates much of the boilerplate to stand up a regionalized Go service from source using `ko_build`.
=> Add a module to encapsulate some of our Go service best practices.

cloudevent-broker/main.tf
This should insulate each region's event delivery pipeline from outages affecting other regions.
Fixes: https://github.com/chainguard-dev/terraform-infra-common/issues/53
=> Use regional storage for pubsub topics

cloudevent-broker/README.md
I noticed that the name of the regional environment variable was `PUBSUB_TOPIC` but we pass in the regional service's URI, so renaming it.
=> Fix the name of the regional environment variable.

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/bigquery.tf, modules/cloudevent-recorder/recorder.tf
Generally I have trained myself to use `_iam_member` because of the likelihood for `binding` to stomp on each other, but in the case of certain resources `binding` is the most appropriate resource to use.
From some internal docs I'm working on:
```
> Guidance: when the resource in question is an implementation detail of
> the module, then the module should leverage `binding` to grant its identities
> exclusive access to interact with the resource.  But when a resource is shared
> and a module is one consumer with incomplete knowledge of the ACL membership
> then it should use the `member` form.
```
=> Migrate several `_iam_member` to `_iam_binding` rules.

modules/cloudevent-trigger/main.tf
By default pubsub subscriptions live for 31d since their last activity.  We don't want our subscriptions to expire.
=> Have subscriptions live indefinitely.

.github/workflows/documentation.yaml, modules/dashboard/service/dashboard.tf, modules/regional-go-service/main.tf, modules/serverless-gclb/README.md, modules/serverless-gclb/main.tf, modules/serverless-gclb/variables.tf
This makes putting regionalized services behind GCLB with DNS and TLS much easier.
=> Add a `serverless-gclb` module.

hack/update-docs.sh, modules/networking/README.md, modules/networking/main.tf, modules/networking/variables.tf
Previously this would try to assign a CIDR block starting from 1.
e.g. given cidr = "10.0.0.0/8" and regions = ["a", "b"], you would get:
a: "10.1.0.0/16"
b: "10.2.0.0/16"
Since this always starts at 1, this makes it difficult to be able to select a subnet range. This change adds a field to start subnet numbering at a specific number (starting at 0).
e.g. with the previous example and netnum_offset = 10, you would now get:
a: "10.10.0.0/16"
b: "10.11.0.0/16"
This is a breaking change if downstream consumers are sensitive to subnet netnum needing to start at 1, but can easily be fixed by adding the netnum_offset. I think we want to do this long term so we don't leave IPs with 0 unassigned.
=> networking: Allow configurable netnum offsets.

modules/regional-go-service/README.md, modules/regional-go-service/main.tf, modules/regional-go-service/variables.tf
This covers the case where the network may not be in the same project, and the permission to use the network is not granted by the host project run.serviceAgent role.
Should resolve this error: https://github.com/chainguard-dev/mono/actions/runs/7647002860/job/20871902146#step:16:160
=> regional-go-service: grant compute.networkUser to Cloud Run service account.

modules/regional-go-service/README.md, modules/regional-go-service/main.tf, modules/regional-go-service/variables.tf
Reverts chainguard-dev/terraform-infra-common#82
This is the wrong service account to receive this grant, so rolling this back.
=> Revert "regional-go-service: grant compute.networkUser to Cloud Run service account."

modules/dashboard/sections/resources/main.tf
making this a stacked bar graph as startup happens infrequently, causing the line graph to be very broken
bar graph will give a sense of how long startup was taking when it happens.
=> change startup latency graph from line to stacked bar

modules/dashboard/widgets/latency/main.tf
the latency widget defaulted to 3 bands, 50, 95, 99
when used in combination with group by fields, it becomes really noisy.
have it default to a single percentile, 99
this hopefully also reduces the load on dashboard page with fewer timeseries needing to be loaded.
this makes the percentile configurable.
=> use only single band for latency graph

modules/dashboard/sections/errgrp/README.md, modules/dashboard/sections/errgrp/main.tf, modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/dashboard/service/variables.tf, modules/dashboard/widgets/errgrp/README.md, modules/dashboard/widgets/errgrp/main.tf, modules/dashboard/widgets/latency/main.tf
will look something like below
cloud run has its own error reporting grouping, have it show in the dashboard
will cover various errors that cloudrun detects 
usage will need to be updated to pass in the project_id
=> add error reporting widget and add it to service dashboard

modules/dashboard/sections/errgrp/main.tf
should be dividing by 4 on height not width.
[sample dash](https://console.cloud.google.com/monitoring/dashboards/builder/f7a35b30-7561-4fbf-bbe3-500d9c9dab52;duration=P1D?project=kleung-chainguard&supportedpurview=project&f.rlabel.service_name=enforce-registry)
=> fix height/width for errgrp widget in service dashboard

modules/otel-collector/cmd/otel-collector/kodata/config.yaml
Some of these are based on the default settings from the official sidecar, which we should eventually switch over too.
=> Tune otel collector GMP exporter settings

modules/otel-collector/cmd/otel-collector/kodata/config.yaml
Previously I removed this because it didn't seem important to know the instance ID. However, `instance` turns out to be a uniqueness constraint that GMP treats specially.
Adding back to avoid time series collision issue.
=> Add instance to metrics

modules/audit-serviceaccount/README.md, modules/audit-serviceaccount/main.tf
I get this trying to deploy it:
```
Alert policies with a log matching condition can only have a single condition
```
So much for just testing these in the log viewer :(
=> Split the GSA alert policies into two

modules/regional-go-service/main.tf
It appears that Cloud Run v1 entries have a different shape in the audit logs.
=> Expand the data access query

modules/cron/README.md, modules/cron/main.tf, modules/regional-go-service/main.tf
1. Switch `logName` to admin activity (excl. system events and data access)
The `logName` addition pointing at `data_access` excluded mutations, which is the key thing we want to monitor, and most of what that left was things we want to ignore because GetService is pretty benign and common via the console.
2. Split a separate alert policy off for RunJob monitoring
This is the main exception that IS data_access, so for simplicity just make this it's own alert policy.
=> This fixes the cloud run policies in a few ways.

modules/bucket-events/README.md, modules/bucket-events/dashboard.tf
This is basically copy/paste from the broker's ingress dashboard.
Example: https://console.cloud.google.com/monitoring/dashboards/builder/1907212f-1f10-4e62-994f-e37694a766e7;duration=PT15M?project=jason-chainguard&f.rlabel.service_name=bucket-events
=> bucket-events: add dashboard

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/main.tf
This creates an alert policy around the GCS bucket that sits between the recorder and BQ DTS to ensure that nothing outside of this module is mucking with our implementation details.
Fixes: https://github.com/chainguard-dev/terraform-infra-common/issues/146
=> Add an alert policy around the recorder's GCS bucket

.github/workflows/documentation.yaml, .github/workflows/validate.yaml, modules/github-gsa/README.md, modules/github-gsa/main.tf, modules/github-gsa/outputs.tf, modules/github-gsa/variables.tf, modules/github-wif-provider/README.md, modules/github-wif-provider/main.tf, modules/github-wif-provider/outputs.tf, modules/github-wif-provider/variables.tf
There are two key modules that work in concert:
1. A provider module, which sets up attribute mappings in a way that we can access interesting claims and do some fuzzy matching,
2. A service account module, which provisions Google Service Accounts that can be provisioned by providers created with the above.
These rules are intended to encapsulate some of the heroics that folks must currently do with CEL to try and get workflow-level authorization to assume particular GSA's, and give us a stronger "subject" for how these workflows appear as principals in audit logs.
=> Add GitHub->GSA federation helper modules.

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/outputs.tf
This is to let us use `google_bigquery_table` to create views of the data once the dataset is created.
=> Add a few outputs to `cloudevent-recorder`

modules/cloudevent-trigger/README.md, modules/cloudevent-trigger/main.tf, modules/cloudevent-trigger/variables.tf
https://cloud.google.com/pubsub/docs/subscription-message-filter#filtering_syntax
This adds a new input var, `filter_prefix`, which works like `filter` but with attribute prefixes instead of exact matches.
=> cloudevent-trigger: support filter prefix

modules/cloudevent-recorder/bigquery.tf
```
Error: Invalid index
on .terraform/modules/event-recorder-cloudrun/modules/cloudevent-recorder/bigquery.tf line 146, in resource "google_monitoring_alert_policy" "bq_dts":
146:         AND resource.labels.config_id = "${element(reverse(split("/", google_bigquery_data_transfer_config.import-job[conditions.key].name)), 0)}"
├────────────────
│ conditions.key is "us-central1"
│ google_bigquery_data_transfer_config.import-job is object with 6 attributes
The given key does not identify an element in this collection value.
```
=> used wrong index, needed to duplicate the key, ${region}-${type} for the transfer config

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/bigquery.tf, modules/cloudevent-recorder/variables.tf, modules/dashboard/sections/resources/README.md, modules/dashboard/widgets/latency/README.md
Allows callers to pass in an optional partition field to instruct BQ for how to partition the data. If omitted, default behavior is used (import time).
=> [cloudevent-recorder] Add partition_field option.

modules/regional-go-service/README.md, modules/regional-go-service/main.tf
from the issue with `empty_dir` causing revision rollout to fail unnoticed.
=> monitoring: alerting when cloud run revision fails to rollout

modules/regional-go-service/main.tf
```
│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].filter had an invalid value of "        resource.type="cloud_run_revision"
│         resource.labels.service_name=nghia-cr-dev-api"
│         severity=ERROR
│         protoPayload.status.message:"Ready condition status changed to False"
│ ": Unparseable filter: syntax error at line 2, column 54, token '"
│         severity=ERROR
│         protoPayload.status.message:"'
│ 
│   with module.api.module.api-service.google_monitoring_alert_policy.bad-rollout,
│   on ../../../../terraform-infra-common/modules/regional-go-service/main.tf line 249, in resource "google_monitoring_alert_policy" "bad-rollout":
│  249: resource "google_monitoring_alert_policy" "bad-rollout" {
```
=> bug: fix missing quote for alert

modules/github-gsa/main.tf, modules/github-wif-provider/main.tf
The `google.subject` claim is limited to 127 characters, which for certain repo names (e.g. `chainguard-dev/terraform-provider-chainguard`) is too small.
To mitigate this, we dump the repository name being explicitly separate and instead rely on the name that prefixes the `workflow_ref`.
There are a handful of additional changes here:
1. Switch to `[|]` for escaping the pipes, so they are not treated as disjunctions,
2. Wrap the inner regex in parenthesis, so `^(...)$` matches the hole string and the `|` characters don't mistakenly become disjunctions,
3. Include the (missing!) repository prefix in our GSA audit regular expression.
I tested this by modifying the existing secret alert policies to use this and it properly filters the authorized usage:
``` …
```
=> Change our attribute mapping to fit in character limits.

modules/regional-go-service/main.tf
When a revision fails to rollout, 2 audit logs are triggered that look very similar. One is for the revision, one is for the service.
This condition seems to be targeting revisions, so filter on that kind.
=> regional-go-service: Only alert on failed revisions, not failed services

modules/otel-collector/cmd/otel-collector/kodata/config.yaml
Trace exports to sidecar doesn't work as expected and causing log spams. Turning it off for now.
=> Sidecar not to export traces

pkg/httpmetrics/metrics.go
Simply importing the package serves the endpoints. When the service is public, these endpoints are public, and that's Bad.
> To use pprof, link this package into your program:
> 
>     import _ "net/http/pprof"
=> httpmetrics: disable pprof endpoints

modules/cron/main.tf
do not alert when provisioner runs a cloudrun job.
=> alerting : exclude provisioner for alerting on running cloud run job

modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/cloudevent-receiver/variables.tf, modules/dashboard/service/README.md, modules/dashboard/service/dashboard.tf, modules/dashboard/service/variables.tf
This also makes it possible for callers to omit the HTTP or GRPC sections, e.g., if the service doesn't serve those.
The default behavior should match what we have today, but dashboards that would benefit from seeing GitHub API metrics can now have that.
GitHub API metrics aren't service-specific, so this graph might be misleading in some cases. At least showing it to people should make it easier to iterate on it.
=> optionally include GitHub metrics in dashboards

modules/prober/alert.tf
Tune the SLO alert aggregations to better match the reported uptime percent by the probers. The two aggregations 
1. take the mean uptime percent over a day across all regions
2. take the mean of that aggregation across a rolling 1 day window to flatten into a step graph of 1 day resolution.
=> tune the slo alert aggregations

modules/github-bots/blocker/blocker.go, modules/github-bots/blocker/main.go, modules/github-bots/dnm/dnm.go, modules/github-bots/dnm/main.go, modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go, modules/github-bots/time/main.go, modules/github-bots/time/time.go
refactors the bot to use `Handlers` that get explicitly registered in place of the implicit interfaces.
this doesn't solve the `event` -> `*github` serialization, but makes the creation of bots and their associated functions a little more ergonomic.
this also adds a case for the `workflow_run` event, and hoists the serialization out into a function until we can tackle this with codegen
=> use handlers for the gh bot

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/bigquery.tf, modules/cloudevent-recorder/variables.tf
From this page: https://cloud.google.com/bigquery/docs/cloud-storage-transfer#bq
If this works as documented, we can avoid pre-filtering GH event payloads before they enter the broker, and rely on DTS to drop fields outside our schema all the way "to the right".
We could then make our BQ schemas more of an implementation detail, and internal to schemagen, and GH event subscribers could get the full GH event payload whether or not the fields end up getting recorded.
=> cloudevent-recorder: ignore unknown values

modules/github-bots/sdk/bot.go, modules/github-events/README.md, modules/github-events/cmd/trampoline/main.go
Also fix a typoe in bot.go that made octo STS requests not bucketed in metrics.
=> github-events: forward all GH events, document recorder usage

pkg/httpmetrics/metrics.go, pkg/httpmetrics/transport.go
This always matches service and we never use it.
=> Drop configuration name.

modules/cloudevent-broker/cmd/ingress/main.go
This tracks the (Google-)verified identity that was used to send the event.
=> Automatically populate `ce-actor` in our ingress service.

modules/regional-go-service/README.md, modules/regional-go-service/main.tf, modules/regional-go-service/otel-config/config.yaml, modules/regional-go-service/variables.tf
this allows us to avoid building a new image to include the otel config file.
seeing metrics in my dev env
=> use base otel with config via env

modules/cloudevent-broker/README.md, modules/cloudevent-broker/ingress.tf, modules/cloudevent-broker/variables.tf, modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/recorder.tf, modules/cloudevent-recorder/subscriber-gcs.tf, modules/cloudevent-recorder/variables.tf
pass down the limits clause to `regional-go-service` so the user of the `broker` and `recorder` can set resource limits appropriately.
this reverts a previous change to increase the memory for recorder statically.
=> make resource limits configurable for broker and recorder

pkg/httpmetrics/metrics.go
this change adds back pprof.
as part of this lib, we reset the default serve mux in `init()` to remove the pprof handler registration so it is not exposed by default.
https://github.com/golang/go/issues/42834#issuecomment-1752610216
https://gist.github.com/sudo-suhas/9cd7fae904b94f93730843b118729230#access-control
=> pull in pprof, but reset DefaultServeMux to not register pprof by default

modules/cloudevent-recorder/cmd/dejavu-bq/README.md, modules/cloudevent-recorder/cmd/dejavu-bq/main.go
Add [dejavu-bq](https://github.com/chainguard-dev/dejavu-bq) to the recorder as a replay utility. This should replay any bigquery data returned from the specified query as cloudevents.
=> Add dejavu-bq as recorder cmd

go.mod, go.sum, modules/cloudevent-broker/cmd/ingress/main.go, modules/cloudevent-recorder/cmd/recorder/main.go, pkg/profiler/profiler.go
a secure way to get profiling data while running on gcp
https://cloud.google.com/profiler/docs/profiling-go
if we decide to adopt `cloud profiler` across the board, we may consider ripping out `pprof` completely
we can use `pprof`, but we would have to register the `pprof` endpoints on the application port, as cloudrun only allows a single port.
we can block external traffic to `/debug/pprof` with cloud armor, and only access via the `*.run.app` host
both options would require enabling
pprof would still require
- tunneling
- curl endpoint with identity token
=> allow cloud profiler to be used

modules/regional-go-service/README.md, modules/regional-go-service/main.tf, pkg/httpmetrics/metrics.go
turn on debug logging while setting this up initially
it does work
https://console.cloud.google.com/profiler/cr-dev-api/cpu?referrer=search&project=kleung-chainguard&supportedpurview=project
=> grant profiler agent role to SA in regional-go-service

pkg/httpmetrics/metrics.go
see https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190
=> bug: workaround to stop memory leak in otel

.github/workflows/validate.yaml, modules/cron/example/example.tf
rather than maintain a list of tf module dirs, run validate on all dirs with *.tf files
=> run validate on all tf dirs

modules/github-bots/blocker/blocker.go, modules/github-bots/dnm/dnm.go, modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go, modules/github-bots/time/time.go
https://github.com/chainguard-dev/terraform-infra-common/pull/270 means we're forwarding the full event now, which means we can drop the extra, now redundant *github type from the bot handlers
=> drop the now redundant *github type from the handlers

modules/cron/main.tf
follow up from https://github.com/chainguard-dev/internal/pull/3773#discussion_r1585827887
=> grant project cloudrun viewer only to groups

modules/dashboard/sections/resources/main.tf
mean resource utilization doesnt show the peaks
use 99 percentile to see when we saturate resources
=> use 99 percentile for resource utilization, not mean

pkg/httpmetrics/idtoken.go, pkg/httpmetrics/idtoken_test.go, pkg/httpmetrics/testdata/creds.json, pkg/httpmetrics/transport.go, pkg/httpmetrics/transport_test.go
This function is based on https://github.com/googleapis/google-api-go-client/blob/v0.178.0/idtoken/idtoken.go#L46
but skipping the opts validation that can't be performed here because private types.
We can't just use the `option.WithHTTPClient` and call upstream `idtoken.NewClient()` because that code always tries to cast from the `http.DefaultTransport` anyway, no matter if `option.WithHTTPClient()` is used or not ([see](https://github.com/googleapis/google-api-go-client/blob/v0.178.0/idtoken/idtoken.go#L73)).
=> Add a clone of idtoken.NewClient() that is more compatible with our metrics Transport

go.mod, go.sum, modules/github-bots/sdk/github.go
Create new `Fetch*` alternative functions for retrieving `io.ReaderAt`s for the helper methods that deal with get'ing arbitrary files from GH (logs and artifacts).
This stops us from arbitrarily buffering the entire contents into memory, and restricts the buffer size to 1mb for now. This currently isn't configurable, but wouldn't be hard to make it configurable if needed.
This also marks the old `Get*` functions as deprecated.
=> support ReaderAt for GH file retrievals

modules/github-bots/README.md
The `source_code` field was removed, which is misleading in the docs
=> Remove non-existent field from docs

modules/bucket-events/README.md, modules/bucket-events/main.tf, modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/subscriber-gcs.tf, modules/cloudevent-trigger/README.md, modules/cloudevent-trigger/main.tf
This would retain dead-letter messages for further inspection. It also allows alerting based on better metrics, for example the number of dead-lettered messages:
The new metrics are better than the publish rate to the DLQ, it's hard to tell from the publish rate if a 100 messages were dead-lettered or only 1.
=> Add a pull subscription to the dead-letter topics

modules/github-bots/sdk/github.go
turns out the `logs` endpoint is:
1. different than the `artifacts` endpoint
2. doesn't support `Range` 😠 
in light of that, add `store` as a required variable for the caller to create, seeing that it must properly be closed as well. this exposes the caller to `httpreaderat` which I don't love, but its simple to implement and seems worth it for easy conditional buffering
this also changes the return signature to a `*zip.Reader`, since it appears logs are also returned as zip files
=> require a store for buffering

modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go
Add a new handler for bots subscribing to `lofo` events https://github.com/chainguard-dev/mono/blob/main/bots/lofo
Once this is merged I can have lofo use `sdk.WorkflowRunArtifactEvent` so there is a single source of truth for the name across repos.
=> github-bots: Add workflow run artifact handler

modules/cron/main.tf
```
│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alertStrategy.notificationRateLimit had an invalid value of "period 	 { seconds: 3600 }": metric-based alert policies must not specify a notification rate limit
│ 
│   with module.notify-automation.module.populate-apkmetadata-cron.google_monitoring_alert_policy.success[0],
│   on .terraform/modules/notify-automation.populate-apkmetadata-cron/modules/cron/main.tf line 331, in resource "google_monitoring_alert_policy" "success":
│  331: resource "google_monitoring_alert_policy" "success" {
│ 
╵
Error: Process completed with exit code 1.
```
=> fix: remove conflicting property for cron success alert

modules/github-bots/sdk/github.go
Now that we are generating more artifacts in the release, they won't all fit into the default page size. This just adds a function to search each page for an artifact before retrieving the next page.
=> Add paginated artifact list

cmd/replayer/main.go
This tool uses the local gcloud credentials to listen to a pull subscription (intended for the pull subscription we created by default for each dead letter topic), and send it back to a topic (the original topic).
Example usage: 
```
❯ go run . --source=nghia-...-dlq-pjxu --dest=nghia-...-us-central1 --projectID nghia-...
Listening for messages.
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Found message: { "content": "this is a test" }
Replayed message: { …
```
=> Tool to replay a pull subscription to a topic

modules/cloudevent-recorder/README.md, modules/cloudevent-recorder/recorder.tf, modules/cloudevent-recorder/variables.tf, modules/dashboard/cloudevent-receiver/README.md, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/cloudevent-receiver/variables.tf
Slack context: https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1715107930859599
We hit widget limits when adding more event types to the recorder. This is a pass at modifying the dashboard module to stay below the widget limit by creating a dashboard per trigger.
=> Create a dashboard per trigger to stay under widget limit

pkg/httpmetrics/transport.go
Currently it is like this:
After fix:
=> Fix the nesting of http metrics Transport span

pkg/httpmetrics/metrics.go
otel uses this as the span display name (must be non-empty).
=> Specify handler name for otelhttp

modules/bucket-events/cmd/trampoline/main.go, modules/cloudevent-broker/cmd/ingress/main.go, modules/cloudevent-recorder/cmd/recorder/main.go, modules/github-bots/sdk/bot.go, modules/github-events/cmd/trampoline/main.go, pkg/httpmetrics/cloudevents/client.go
This will automatically add a span with said name around event handling. Currently that span is always named "cloudevents" which is confusing/redudant.
Intentionally break backward compat here to make sure all our usage to include a name.
=> `mce.NewClientHTTP` to require name

pkg/httpmetrics/metrics.go, pkg/httpmetrics/preserve_traceparent.go, pkg/httpmetrics/transport.go
Similar to https://github.com/chainguard-dev/go-grpc-kit/pull/268, this saves the traceparent header before sending an HTTP request and restore it on the server side.
This avoids missing Cloud Run span causing broken trace hierearchy.
=> preserve original trace headers for http

modules/regional-service/README.md, modules/regional-service/main.tf
```
│ Error: Error creating AlertPolicy: googleapi: Error 400: Alert policies with a log matching condition can only have a single condition.
│ 
│   with module.oidc-cloudrun.module.impersonation-service.module.this.google_monitoring_alert_policy.crash,
│   on .terraform/modules/oidc-cloudrun.impersonation-service/modules/regional-service/main.tf line 369, in resource "google_monitoring_alert_policy" "crash":
│  369: resource "google_monitoring_alert_policy" "crash" {
```
=> fix broken alert

modules/regional-service/README.md, modules/regional-service/main.tf
Attempting to remove the `fatal` alert from each service to see if that is enough to bring us under 500.
=> remove fatal alert from regional service

modules/alerting/main.tf
```
│ Error: Error updating AlertPolicy "projects/staging-enforce-cd1e/alertPolicies/10888012264146521460": googleapi: Error 400: Field alert_policy.conditions[0].filter had an invalid value of "        logName: "/logs/run.googleapis.com%2Fvarlog%2Fsystem"
│         severity=ERROR
│         textPayload:"Consider increasing the memory limit"
│         -resource.labels.backend_service_name=enforce-staging-ing-vuln"
│ ": Unparseable filter: syntax error at line 4, column 71, token '"'
```
=> remove extra quote that is breaking monitoring in mono

modules/alerting/main.tf
this is different from the previous alert where the panic is printed to stderr/stdout
this panic is exposed as a stacktrace, which the previous alert did not catch.
=> add alert for go panic stacktrace

modules/alerting/main.tf
```
│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_monitoring_query_language.evaluation_missing_data had an invalid value of "EVALUATION_MISSING_DATA_INACTIVE": Conditions setting evaluation_missing_data must have a non-zero duration.
```
fix is to drop evaluation missing data, not needed in this case
=> fix evaulation_missing_data for alerting module

modules/alerting/main.tf, modules/alerting/variables.tf
this can be adjusted for staging where we can set a higher value to avoid false positives, 
while keeping it low for prod to ensure prompt response
=> make duration for the failure rate alert configurable

modules/alerting/main.tf
promql allows checking multiple conditions, mql does not
alert when error rate is above threshold and has non-zero traffic
use custom prometheus metric rather than built-in cloud run revision metric as ours dont count failed health check 5xx which there are no logs for
will track failed health check and system level 5xx separately
=> change service failure rate alert to use promql

modules/alerting/main.tf, modules/alerting/variables.tf
when cloud run failed to scale and when it failed request 
default these to slack only
allow notification channels to be a bit more customizable
=> new alerts to track bad cloud run behavior

modules/alerting/main.tf, modules/alerting/variables.tf
this allows filtering out known problematic services like `ing-vuln`
will set the filter in mono to filter out `ing-vuln` like https://github.com/chainguard-dev/mono/blob/main/env/enforce.dev/iac/999-monitoring/cloudrun.tf#L339
=> add filter for failed request alert

modules/alerting/main.tf
the default subject for promql alerts does not include any labels
set custom subject to include service name to make it clear what it is alerting on.
following the example from https://github.com/hashicorp/terraform-provider-google/issues/16419
=> set alert document subject to include service name

modules/alerting/main.tf
add comment for subject variables reference
`resource.labels.service_name` => `resource.label.service_name` 
drop `s` on `label`
=> fix variable reference in alert subject

modules/alerting/variables.tf
additional filters are optional, setting empty string as default to avoid nagging user of module to specify
=> set defaults for additional alerting filters

modules/cloudevent-recorder/cmd/recorder/main.go
logging for visibility on failed writes
delete file on failed writes to avoid cruft build up
=> log and delete file on failed write in recorder

modules/alerting/main.tf, modules/alerting/variables.tf
Exclude the given service names from the `5xx failure rate` alert.
=> add var to exclude services from 5xx alert

modules/github-bots/sdk/github.go
I am getting some recent `context canceled` errors when adding/removing labels on PRs. I don't have much visibility on the rate limits. That is why I am adding this check to the response to have some visibility.
Logs:  https://cloudlogging.app.goo.gl/aWGt3MRtthPkubZF9
=> validateResponse: check the if rate limit has been reached

modules/cloudevent-trigger/README.md, modules/cloudevent-trigger/main.tf, modules/cloudevent-trigger/variables.tf, modules/github-bots/README.md, modules/github-bots/main.tf, modules/github-bots/variables.tf
the motivation for this is to be able to filter on two types of github events
rather than be restricted to the multiple variables, allow custom crafting the exact filter desired
=> allow specifying raw filter to pubsub for github-bot/trigger

modules/alerting/main.tf
```
│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "        metric.type="pubsub.googleapis.com/topic/send_request_count"
│         resource.type="pubsub_topic"
│         metadata.system_labels."name"=~".*-dlq-.*"
│         metadata.system_labels."name"!=monitoring.regex.full_match(".*ing-vuln-dlq.*")
│ ": Could not parse filter "        metric.type=\"pubsub.googleapis.com/topic/send_request_count\"\n        resource.type=\"pubsub_topic\"\n        metadata.system_labels.\"name\"=~\".*-dlq-.*\"\n        metadata.system_labels.\"name\"!=monitoring.regex.full_match(\".*ing-vuln-dlq.*\")\n"; syntax error at line 3, column 38, token '=~'
│ 
│   with …
```
=> fix filter syntax for dlq alert

modules/alerting/main.tf
```
│ Error: Error creating Metric: googleapi: Error 400: Number of label descriptors must match number of label extractors
│ 
│   with module.global-alert.google_logging_metric.cloud-run-scaling-failure,
│   on .terraform/modules/global-alert/modules/alerting/main.tf line 293, in resource "google_logging_metric" "cloud-run-scaling-failure":
│  293: resource "google_logging_metric" "cloud-run-scaling-failure" {
│ 
╵
╷
│ Error: Error creating Metric: googleapi: Error 400: Number of label descriptors must match number of label extractors
│ 
│   with module.global-alert.google_logging_metric.cloud-run-failed-req,
│   on .terraform/modules/global-alert/modules/alerting/main.tf line 350, in resource "google_logging_metric" "cloud-run-failed-req":
│  350: resource "google_logging_metric" …
```
=> add missing label key for new log based metrics

modules/cron/main.tf
this is to avoid getting errors like
```
│ Error: Failed to retrieve project, pid: , err: project: required field is not set
│ 
│   with module.build.module.job["enterprise"].module.elastic-build-job.google_cloud_run_v2_job.job,
│   on .terraform/modules/build.job.elastic-build-job/modules/cron/main.tf line 33, in resource "google_cloud_run_v2_job" "job":
│   33: resource "google_cloud_run_v2_job" "job" {
```
=> explicitly set project for cloud run job resource

modules/cron/README.md, modules/cron/main.tf, modules/cron/otel-config/config.yaml, modules/cron/variables.tf
prometheus metrics are scrapped
otel sidecar does scrapping for prometheus metrics and push to gcp
still need to verify if it works
but i did verify that it doesnt break things
=> metrics sidecar for cloudrun job

modules/cloudevent-recorder/cmd/recorder/main.go, modules/github-bots/sdk/bot.go, modules/github-events/cmd/trampoline/main.go, pkg/httpmetrics/metrics_test.go, pkg/httpmetrics/transport_test.go
This should let subscribers filter on only repos they care about, and only actions they care about (e.g., PR opened but not closed, etc.)
Also clean up some lint findings.
=> gh bots: add action and subject to event message

go.mod, go.sum, modules/bucket-events/cmd/trampoline/main.go, modules/cloudevent-broker/cmd/ingress/main.go, modules/cloudevent-recorder/cmd/dejavu-bq/main.go, modules/cloudevent-recorder/cmd/logrotate/main.go, modules/cloudevent-recorder/cmd/recorder/main.go, modules/github-bots/sdk/bot.go, modules/github-events/cmd/trampoline/main.go, pkg/httpmetrics/metrics.go, pkg/profiler/profiler.go
This seems to be more updated than kelseyhightower/envconfig, and it has a `MustProcess` that returns the value, meaning it can be used as an init-time package variable.
=> migrate to sethvargo/go-envconfig

modules/github-bots/sdk/github.go
Since we are doing our own token reuse and revocation, the wrapping done by oauth2.NewClient doesn't work, since it reuses tokens until they expire. Our tokens don't set an expiry, so they never expire.
=> github: Avoid redundant token reuse wrapper

modules/github-bots/sdk/github.go
The theory is that calling `Token` revokes the old token, which gets reused by `ReuseTokenSource` inside of the GitHub client.
Just reaching in and using the token directly should avoid this, if the theory is correct.
=> github: don't clone by calling Token()

.github/workflows/go-test.yaml, .github/workflows/style.yaml, go.mod, go.sum
function in main line now
https://github.com/googleapis/google-cloud-go/issues/4665#issuecomment-2297676212
bump to go 1.23
=> remove replace dep for trace 

modules/regional-service/main.tf
Once we have labels in Cloud Run we can use the billing data which is exported to BQ to write some queries and help see where we are spending.
=> Add default labels to Cloud Run services to track cost

modules/regional-service/main.tf
These are the labels that GCP billing will ingest into BQ, it ignores the labels at the metadata level.
gcp docs: https://cloud.google.com/run/docs/configuring/services/labels#terraform
=> regional-service: add labels to Cloud Run template

modules/serverless-gclb/README.md, modules/serverless-gclb/main.tf
google provider 6.x.x just came out today
and a lot of google modules havent been updated to support 6.x.x
our module with no version restrictions, defaulted to using the latest, which broke validation as it had breaking change
fixed it, but due to google modules not supporting it, we need to use 5.x.x for the time being
restrict the module to < 6.0.0 until all google modules support 6.x.x
=> pin google provider to less than 6

modules/dashboard/job/dashboard.tf
jobs are created with the `cron` module, that appends `-cron` suffix to the name
everyone passes the name without the suffix
add back the suffix in the dashboard
=> fix job dashboard

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
primary to catch `Container terminated on signal 9.` log where a container was killed.
generalized it to pick up any non-(0|1) log, and picked up 2 instances of signal 7
`ing-vuln` frequently triggers sig 9.
as its a known issue and deprecated, explicitly ignore.
=> alert for container terminated

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
this is to allow ignoring known upstream issues.
=> add support for additional panic filter

modules/alerting/main.tf
logs based alerts doesnt re-trigger, it triggers a new instance
set these alerts to auto-close after an hour to avoid cluttering active alert list
=> tune down auto-close for logs based alerts

pkg/workqueue/dispatcher/dispatcher.go
I realized this wasn't properly threaded when opening: https://github.com/chainguard-dev/terraform-infra-common/issues/554 spelling out how to save/restore trace headers.
=> Use `oip.Context()` in dispatcher to enable trace threading (later).

modules/github-events/cmd/schemagen/main.go, modules/github-events/main.tf, modules/github-events/schemas/event_types.go, modules/github-events/schemas/projects_v2_item.schema.json
This allows the capture of changes in field status from GitHub projects inside an organization.
The `changes` field can have many different forms. To capture everything, we save it as a JSON field to BigQuery. This change was tested in my dev environment.
=> feat(github-events): Record projects_v2_item events

modules/github-bots/sdk/bot.go, modules/github-bots/sdk/handlers.go
- Will enable building bots that react to changes in a GitHub project
=> feat(github-bots): Add support for projects_v2_item events

modules/github-bots/sdk/github.go, modules/github-bots/sdk/ratelimit.go, modules/github-bots/sdk/ratelimit_test.go
wrap the default client in a secondary rate limiter, the intent is for a transparent client side rate limiter tailored for GH's secondary rate limiter
=> add a secondary rate limit waiter to the github client

pkg/workqueue/conformance/conformance.go, pkg/workqueue/conformance/durability.go, pkg/workqueue/gcs/gcs.go, pkg/workqueue/inmem/inmem.go, pkg/workqueue/interface.go
As I added Priority and (not here) NotBefore, the conformance tests being a single enormous test made it really tedious to iterate on failures.
This changes the tests to be much more focused and able to run in isolation on a clean workqueue, so we can `-run` a very specific semantic test.
The GCS conformance tests pass with this:
```
WORKQUEUE_GCS_TEST_BUCKET=mattmoor-testing-workqueue go test -timeout=10m -count=1 ./pkg/workqueue/gcs
ok      github.com/chainguard-dev/terraform-infra-common/pkg/workqueue/gcs      147.560s
```
=> Refactor the conformance tests to be better isolated.

pkg/workqueue/conformance/conformance.go, pkg/workqueue/gcs/gcs.go, pkg/workqueue/gcs/gcs_test.go, pkg/workqueue/inmem/inmem.go, pkg/workqueue/inmem/inmem_test.go, pkg/workqueue/interface.go
This change adds a `NotBefore` option to the workqueue (not exposed via the proto yet), which directs the implementations to delay when certain keys appear in the queue for processing.
This same mechanism is now used to add a back-off when requeuing keys that carry a priority to keep failing high-priority tasks from starving low-priority tasks (h/t Nghia for thinking of this scenario).
```
WORKQUEUE_GCS_TEST_BUCKET=mattmoor-testing-workqueue go test -timeout=10m -count=1 ./pkg/workqueue/gcs
ok      github.com/chainguard-dev/terraform-infra-common/pkg/workqueue/gcs      262.813s
```
=> Add a `NotBefore` option, use it for back-off during retries.

modules/github-bots/README.md, modules/github-bots/main.tf, modules/github-bots/outputs.tf, modules/github-bots/variables.tf
Allow passing a service account instead of always creating a service account.
=> github-bots: optionally use a pre-defined service account email

modules/cron/main.tf, modules/regional-service/main.tf
this is to reduce no-op diffs
example
```
~ resource "google_cloud_run_v2_service" "this" {
id                      = "projects/staging-enforce-cd1e/locations/us-central1/services/build-extras"
~ launch_stage            = "GA" -> "BETA"
```
ignored example;
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#example-usage---cloudrunv2-job-limits
=> default launch stage now that vpc access is GA

modules/alerting/main.tf
the idea is that the rollout is triggered by someone, and that person would be aware of it, so no need to further page.
this also supports individual stage/service rolling which may not be worthwhile to alert.
we may revisit this and have it page for critical services like api/issuer/datastore
=> change bad rollout to non-paging

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
for https://github.com/chainguard-dev/internal-dev/issues/1619
=> add support for pubsub channel in alerting module

modules/alerting/main.tf
for https://github.com/chainguard-dev/internal-dev/issues/4886
this is to allow creating global alerts filtered by squads/teams
=> alerting: dont create metrics for squad alerts

modules/alerting/main.tf
This reverts commit e6a192053e39cb60dcc6e25095542f0f9b2d9a72.
team label is now available on prometheus metrics.
for https://github.com/chainguard-dev/internal-dev/issues/4886
=> rollforward Revert "disable rate squad alerts (#637)"

modules/github-bots/sdk/github.go, modules/github-bots/sdk/github_integration_test.go, modules/github-bots/test/main.go
On the ai remediation bot, we need to search for specific filenames on a repository such as go.mod, pyproject.toml, Cargo.toml... If these files are found then we get the content specifying the path using another existing function GetFileContent which would be used to generate a precise patch.
=> github-bots: add a function to search for a filename in a repo

modules/gke/main.tf, modules/gke/outputs.tf, modules/gke/variables.tf
=> add gke module

modules/github-bots/sdk/check/check.go, modules/github-bots/sdk/check/check_test.go
This should help encapsulate some common patterns we use for CheckRuns, so we don't have 6 copies of this stuff everywhere.
=> sdk/check: helper methods for GitHub CheckRun API

modules/github-bots/sdk/check/check.go, modules/github-bots/sdk/check/check_test.go
Callers don't tend to work in `CheckRun`s themselves, but rather `CreateCheckRunOptions`es (to create runs) or `UpdateCheckRunOptions`es (to update them).
There's no built-in method to convert a `CheckRun` into either of those, so we'll just do it ourselves.
To avoid duplication, `UpdateCheckRun()` just calls `CreateCheckRun()` and twiddles its values.
=> check sdk: return {Create,Update}CheckRunOptions

modules/github-events/cmd/trampoline/main.go, modules/github-events/schemas/check_run.schema.json, modules/github-events/schemas/check_suite.schema.json, modules/github-events/schemas/event_types.go, modules/github-events/schemas/issue_comment.schema.json, modules/github-events/schemas/issues.schema.json, modules/github-events/schemas/projects_v2_item.schema.json, modules/github-events/schemas/pull_request.schema.json, modules/github-events/schemas/push.schema.json, modules/github-events/schemas/workflow_run.schema.json
- Adds installation message for identifying GitHub App installations. These won't be present in the legacy repo based webhooks.
- Adds X-GitHub-Hook-ID as an extension to make it filterable by downstream clients.
- Records the incoming event headers in the body payload, which includes useful info for debugging (e.g. delivery IDs).
Part of https://github.com/chainguard-dev/internal-dev/issues/1513
=> github-events: Add installation, hook ID, and headers to event messages.

modules/github-bots/sdk/check/check.go, modules/github-bots/sdk/check/check_test.go
Prior to this the default status was `queued`, which is misleading if a check wants to say it's started and then later finished.
=> Check SDK: support in_progress checks

go.mod, go.sum, modules/github-events/README.md, modules/github-events/cmd/trampoline/main.go, modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go, modules/github-events/main.tf, modules/github-events/variables.tf
Adds the ability for the trampoline to accept multiple secrets. 
This tries to retain the existing behavior of the webhook assuming at least one secret by allowing additional secrets to be specified by a similar `WEBHOOK_SECRET_` prefix.
Additional secrets must be defined and loaded out of band of the module.
Also adds testing for the trampoline to verify behavior.
Part of https://github.com/chainguard-dev/internal-dev/issues/1513
=> github-events: Add multisecret support to trampoline webhook.

modules/github-bots/sdk/github.go
If there are dangling symlinks in the repo, checkout fails with `worktree contains unstaged changes` -- since we're cloning here, there should be no local changes to lose, and we should force the checkout.
=> github sdk: CloneRepo forces checkout

modules/github-events/cmd/trampoline/main.go, modules/github-events/internal/secrets/secrets.go, modules/github-events/internal/secrets/secrets_test.go
1. os.Environ returns a list of `key=value`, not a list of keys
2. Use append instead of overwriting secrets list each time.
=> github-events: fix secrets parsing

modules/github-wif-provider/README.md, modules/github-wif-provider/main.tf, modules/github-wif-provider/variables.tf
this module hasn't been updated in a while, and it seems to have fallen into a broken state.
```
╷
│ Error: Error creating WorkloadIdentityPoolProvider: googleapi: Error 400: The attribute condition must reference one of the provider's claims. For more information, see https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines#conditions
│
│   with module.github_wif.google_iam_workload_identity_pool_provider.this,
│   on .terraform/modules/github_wif/modules/github-wif-provider/main.tf line 8, in resource "google_iam_workload_identity_pool_provider" "this":
│    8: resource "google_iam_workload_identity_pool_provider" "this" {
```
according to https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines#conditions, for GH WIF, the …
=> add GH required attribute_condition

modules/github-bots/sdk/github.go
When upgrading this module, any `AddComments` will now be required to pass the botName.
=> github-bots: add new botName field to AddComment signature so it works like SetComment.  This helps fetch and identify all comments from specific bots

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
this is in response to github event trampoline failing without errors
and when scanner auth failed
one alert for http, one for grpc
=> alerts to catch 4xx type errors

go.mod, go.sum, modules/github-bots/sdk/github.go
This adds an option to create a client directly with an Apps transport. This allows clients to use their own GitHub App instead of using an OctoSTS client.
=> github-bots: Add direct GitHub App authentication to bot sdk.

modules/github-events/cmd/trampoline/main.go, modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go
Adds an option to only listen to check_run only webhook events for specific webhooks.
In our current deployment, we have multiple webhooks that funnel into the trampoline from multiple sources. Some are repo-level webhooks, some are org-level webhooks. We want to move to a model where we route all of these through a GitHub App, but to do this without downtime or sending duplicate events is tricky. This aims to solve this by restricting a specific webhook to only events that are unique to GitHub Apps - requested check_{run,suite} events.
This will allow us to rollout the new webhook but only pass through these specific events. Once we verify they work, then we can ignore the old webhooks and fully trust the new webhook all in one deployment.
1. WEBHOOK_ID=nil REQUESTED_ONLY_WEBHOOK_ID=nil …
=> github-events: Add WEBHOOK_ID and REQUESTED_ONLY_WEBHOOK_ID filters

modules/github-events/README.md, modules/github-events/main.tf, modules/github-events/variables.tf
See https://github.com/chainguard-dev/terraform-infra-common/pull/689 for impl
=> github-events: Add tf vars for webhook id env vars

modules/prober/README.md, modules/prober/alert.tf, modules/prober/main.tf, modules/prober/variables.tf
update default to expect two failures before failing
=> make uptime alert duration configurable

modules/prober/README.md, modules/prober/alert.tf, modules/prober/variables.tf
this should fix the issue that prevented the prober uptime check alert from triggering during r2 outage
=> change to prober alert to align with probe period

modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go
Some events (`projects_v2_item`) don't have an associated repo, so it's not present in the message. They all should have the organization field (spot checked this on `projects_v2_item` and `check_run.completed`).
=> github-events: Use organization field for org filter.

modules/gke/main.tf, modules/gke/variables.tf
Even though the [documentation for `google_node_pool.network_config` states you can use a blank value for `pod_ipv4_cidr_block`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#nested_network_config), this throws an error on `terraform plan/apply`. It also appears to be a known issue. Instead, only set the block if values are passed, otherwise `null` reverts to defaults. 
Also pass `enable_private_nodes` for cluster config as a variable.
=> refactor node pool network configs to use dynamic and pass `enable_private_nodes` as var

modules/cron/README.md, modules/cron/main.tf, modules/cron/variables.tf
Currently the cron module will perform a `ko` build atop a given base image. This PR expands it to make `importpath` optional, in which case we just run the base image itself.
This is useful in case we want to use `cron` module with `apko`, to customize the command or the `run-as` user.
=> enable cron module to run non-Go images

modules/cron/README.md, modules/cron/main.tf, modules/cron/variables.tf
Because `oci::parse` only accepts digests, don't call it when `importpath=""` for backward compatibility. I will follow up with another fix to also accept tags for when `importpath=""`, but for now this should fix the broken backward compatibility introduced in #734
=> cron: don't parse base_image when importpath=""

modules/alerting/main.tf
need \\\\ for \ for re2
first is to escape terraform
second is to escape string field in api
\\\\ => \\ => \
=> fix escaping for label extractor for exit code alert policy

modules/github-bots/sdk/github.go
I found myself wanting to use the `go-git` library in the same context as using this `GitHubClient`.
The `GitHubClient` seems awesome as a centralized, elegant way to handle OctoSTS auth, that automatically does all the right things.
But then I wanted to do more git things to the repo. For example, I wanted to clone a repo, but I didn't want to do all of the specific maneuvers that the `GitHubClient`'s existing `CloneRepo` method does. I wanted the power of the raw `go-git` library, but I didn't want to have to reinvent an auth solution when I do that.
Let me know if there's a better solution to this problem!
=> feat(sdk): new GitAuth method on GitHubClient

modules/cloudevent-recorder/bigquery.tf
we shard on type, so we should include the type in the alert name
=> fix alert name for bigquery data transfer service

modules/cron/main.tf, modules/cron/otel-config/config.yaml, modules/regional-service/main.tf, modules/regional-service/otel-config/config.yaml
To avoid the plugin crashing when metadata server has not come up yet.
=> Add `project_id` in googlemanagedprometheus config

modules/alerting/main.tf, modules/alerting/variables.tf
Adds a new filter variable to allow selective alerting for the nonzero-exitcode alert. This needs a new var, since the existing squad_log_filter is too broad (e.g. you
may want to disable exit code alerts without disabling the others).
=> alerting: Add exitcode filter

modules/cron/variables.tf
The alignment period + duration of a request can't be greater than 25h. We hardcode the duration to `alignment_period/4`, which caps how big `alignment_period` can be to `20h`. Add validation on this var to avoid pushing incorrect values unknowningly.
=> add validation for `success_alert_alignment_period_seconds`

modules/prober/README.md, modules/prober/main.tf, modules/prober/variables.tf
This commit enables `deletion_protection` to prevent probes from accidental deletion.
=> prober: add `deletion_protection` to the prober module

CLAUDE.md, pkg/workqueue/gcs/gcs.go, pkg/workqueue/gcs/metrics.go
This change exposes a metric for the maximum number of attempts any task in the queue has seen.  Once this rolls out, we should be able to experiment with charts that plot this metric and potentially alert when tasks pass some threshold (e.g. 10?).
=> Expose a metric for the maximum task attempts seen.

modules/alerting/main.tf, modules/bucket-events/dashboard.tf, modules/cloudevent-broker/ingress.tf, modules/dashboard/alerts/dashboard.tf, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/job/dashboard.tf, modules/dashboard/service/dashboard.tf, modules/github-bots/main.tf, modules/github-events/dashboard.tf, modules/regional-go-service/main.tf, modules/workqueue/dashboard.tf
Prompt:
> Enumerate the latest release by listing the tags on the repository and picking the latest semantic version.  You can compare the current state against a prior version by diffing against a prior tag.  Any moved blocks that were not added in the diff between that tag and HEAD can be removed.  Do this for the newest tag older than 3 months now.
=> Remove moved blocks older than 3mo (all of them)

modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go
Add a new field to CloudEvents indicating when a pull request is merged.
This adds a boolean "merged" extension to events when a pull request has been merged, making it easier for downstream consumers to filter and process merged PRs without having to parse the event payload.
A filter to consume only merged PRs might look like this:
```
filter = {
"type"   = "dev.chainguard.github.pull_request"
"action" = "closed"
"merged" = "true"
}
```
=> github-events: Add merged extension for merged pull requests

modules/github-events/internal/trampoline/server.go, modules/github-events/internal/trampoline/server_test.go
Reduce webhook processing overhead by unmarshalling the JSON payload once instead of four times.
This change improves performance by:
- Parsing the payload into a generic map at the beginning
- Update helper functions that work with already parsed data
- Maintaining full backward compatibility
- Preserving all existing functionality for PR and merged detection
All tests pass with the optimized implementation.
=> github-events: Optimize JSON unmarshalling in webhook handler

modules/alerting/README.md, modules/alerting/main.tf
I propose a change to this alert to also handle runtime panics as part of the condition that fires this alert. I am not so sure we want to fire this alert even if the severity is NOT at the ERROR level. But I'd consider awkward to log panics as just info/warn log entries.
related to: https://chainguard-dev.slack.com/archives/C05CM0DM7RV/p1745920565303639
=> panic_filter: match text regex 'runtime/panic'

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
split existing exit code alert policy into two, one for service and one for jobs
service will use log message with exit code
job will use audit log for execution run to tell if it failed or not
a separate alert policy will be created for the cloud run job where we customize the exit code to differentiate between expected failures and system failures
=> alert policy for cloud run job failures

modules/cloudsql-postgres/README.md, modules/cloudsql-postgres/docs/auth.md, modules/cloudsql-postgres/main.tf, modules/cloudsql-postgres/outputs.tf, modules/cloudsql-postgres/variables.tf
This module provisions a Cloud SQL for PostgreSQL instance with production-ready defaults and convenient toggles for high-availability, automated backups, point-in-time recovery (PITR) and read-replicas.
=> feat: add cloudsql-postgres module

modules/alerting/README.md, modules/alerting/main.tf, modules/alerting/variables.tf
for https://github.com/chainguard-dev/internal-dev/issues/12123
the group by with the reduce mean aggregation was causing the qps to be below the threshold, causing the alert to never trigger.
=> fix grpc error alert

modules/dashboard/sections/gorm/gorm.tf, modules/dashboard/sections/grpc/grpc.tf, modules/dashboard/sections/http/main.tf, modules/dashboard/widgets/xy/README.md, modules/dashboard/widgets/xy/main.tf
for https://github.com/chainguard-dev/internal-dev/issues/12123
drop secondary aggregation unless explicitly specified.
secondary aggregation messes up the graph more often than not and is not normally needed
=> grpc error rate dashboard

modules/cloudsql-postgres/main.tf
like we do in the datastore module, so that any client that tries to connect straight to the instance’s private IP (bypassing the auth proxy) will now be rejected unless it presents a valid client certificate.
=> postgres: enforce ssl

pkg/workqueue/gcs/gcs.go
by ignoring dead-lettered keys.
=> workqueue: fix max-attempt metrics

modules/alerting/main.tf
the field `protoPayload.status.code` isnt populated in this scenario
=> fix exit code extraction for exitcode service alert

modules/redis/README.md, modules/redis/main.tf, modules/redis/outputs.tf, modules/redis/variables.tf
This commit updates the module to automatically manage Redis authentication credentials in Google Secret Manager when `auth_enabled = true`:
- Create a Redis instance with authentication enabled
- Retrieve the GCP-generated auth string
- Store the auth string in Secret Manager with Secret name automatically set to `{name}-auth` (e.g., "my-redis-instance-auth")
- The Secret Manager secret is created in the same project as the Redis instance
- Make the auth string available to authorized service account
=> redis: automatically manage AUTH credentials in Secret Manager

modules/github-gsa/main.tf, modules/github-gsa/variables.tf, modules/github-wif-provider/main.tf
the existing refspec `pull_request` does not work with workflows triggered on `pull_request_target` as the ref for `pull_request` is of the format `refs/pull/[0-9]+/merge` while `pull_request_target` have a ref of the format `refs/heads/[BASE BRANCH]`
for https://github.com/chainguard-dev/terraform-infra-common/issues/746
=> add support for pull_request_target

modules/redis/outputs.tf
Exposes the server CA certificates for the Redis instance as an output
=> redis - add server_ca_cert output for TLS connections

pkg/rotate/blob.go
We're still seeing upload errors after https://github.com/chainguard-dev/terraform-infra-common/pull/810, but the error is not accessible to the logs since it is scoped to the `if` block. Refactor so we can see the error for further debugging.
=> cloud-event-recorder: refactor so `writer.Close()` err is accessible to logs

modules/gke/main.tf
=> gke - fix typo on pod_ipv4_cidr_block

modules/gke/variables.tf
Change the default value for the `pod_ipv4_cidr_block` variable in `modules/gke/variables.tf` from `""` (empty string) to `null`.
When the default is set to `""` (empty string), any configuration value of `null` gets converted to an empty string by Terraform because of `optional(string, "")`. The Google provider rejects an empty string for this field, expecting either a valid CIDR block or no value at all (`null`). By setting the default to `null`, we allow the variable to be truly unset if not specified, which aligns with provider expectations and prevents errors.
=> fix: gke - set default of pod_ipv4_cidr_block to null to prevent invalid empty string

modules/bastion/README.md, modules/bastion/main.tf, modules/bastion/outputs.tf, modules/bastion/variables.tf
Generic jump-host (bastion) module. The primary use case is to provide controlled, break-glass access to resources within a VPC that do not expose a public IP.
Includes an option to install the Cloud SQL Auth Proxy for secure, IAM-based access to Cloud SQL instances, but this is disabled by default. Otherwise, it's generic by design and isn't tied to any specific backend or service.
Needed for https://github.com/chainguard-dev/internal-dev/issues/12794, https://github.com/chainguard-dev/internal-dev/issues/12795
=> feat: add bastion module

modules/bucket-events/dashboard.tf, modules/cloudevent-broker/ingress.tf, modules/dashboard/cloudevent-receiver/dashboard.tf, modules/dashboard/sections/gorm/gorm.tf, modules/dashboard/sections/grpc/grpc.tf, modules/dashboard/sections/http/main.tf, modules/dashboard/sections/resources/main.tf, modules/dashboard/service/dashboard.tf, modules/github-events/dashboard.tf, modules/regional-service/otel-config/config.yaml
previous dashboard relied on the `RESOURCE_LABEL` `service_name` metric, which is only available for built in google cloud run metrics.
to have it work for our custom prometheus metric, we add `METRIC_LABEL` `service_name`
now that we insert a metric `service_name` label for all cloud run services.
we can now leverage the dashboard filter to select the service rather than needing to specify it for each widget
as sections end up having a mix of build-in and custom prometheus metrics, module level filter with `resource.type=cloud_run_revision` no longer apply
add the resource type to each widget and remove the one at the module level
address issue where it dashboard does not filter on service
https://chainguard-dev.slack.com/archives/C083P5AQNQ2/p1750171310685599
=> fix up dashboard filter

modules/github-wif-provider/main.tf
Sometimes people want to pass in longer names.
This has come up in some internal PRs:
- https://github.com/chainguard-dev/infra/pull/433
- https://github.com/chainguard-dev/infra/pull/436
- https://github.com/chainguard-dev/infra/pull/712
I think another good approach would be to validate the `name` variable,
restricting it to 23 characters, and to provide a further `description` variable so that users can provide the full name without truncation.
=> Truncate WIF provider pool display name

modules/cloudevent-recorder/cmd/dejavu-bq/main.go, modules/workqueue/cmd/dispatcher/main.go, modules/workqueue/cmd/inmem/main.go, modules/workqueue/cmd/receiver/main.go, modules/workqueue/cmd/send/main.go
I noticed a few common services weren't optimizing their logs for GCP, which meant they were missing some details (trace ID, source location, correct severity)
This fixes that, anywhere I could find a `cmd/main.go` that looked like a service without the import.
=> clog: ensure gcp logging is enabled

README.md, modules/bastion/main.tf, modules/bucket-events/main.tf, modules/cloudevent-broker/main.tf, modules/cloudevent-recorder/main.tf, modules/cloudsql-postgres/main.tf, modules/configmap/main.tf, modules/gke-ap/main.tf, modules/gke/main.tf, modules/redis/main.tf, modules/regional-service/main.tf, modules/secret/main.tf, modules/workqueue/main.tf
- Follows up from https://github.com/chainguard-dev/terraform-infra-common/pull/913
- Pattern originally introduced in #511
Per feedback in https://github.com/chainguard-dev/terraform-infra-common/pull/913#discussion_r2167352412
I've added documentation as well.
If we think these labels aren't actively used, I'm also happy to remove them. 
If we want to go further into module-based labelling, then it would probably be useful to have a `module: <module-name>` label as well, rather than one where `<module-name>` is the key.
=> Standard convention for labeling by module

modules/secret/main.tf
The use of the `redis` module is causing the `Abnormal Secret Access` alert to fire for `GetSecretVersion`, possibly due to the usage of the `google_secret_manager_secret_version` resource. This is a valid action for an authorized accessor, so ignore this method for the alert.
=> ignore method `GetSecretVersion` in the abnormal secret access alert for authorized accessors

modules/bastion/main.tf
Hit this error when trying to deploy a bastion after `on_host_maintenance = "TERMINATE"` was added.
```
module.bastion.google_compute_instance.bastion: Creating...
Error: -07T14:33:55.068Z [ERROR] provider.terraform-provider-google_v6.40.0_x5: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_detail="" tf_proto_version=5.8 tf_provider_addr=registry.terraform.io/hashicorp/google tf_req_id=b2af8385-cf11-22b6-e2cd-dfb2036f4887 tf_resource_type=google_compute_instance tf_rpc=ApplyResourceChange diagnostic_severity=ERROR diagnostic_summary="Error creating instance: googleapi: Error 400: e2 instances do not support onHostMaintenance=TERMINATE unless they are preemptible., …
```
=> Fix on_host_maintenance

modules/networking/README.md, modules/networking/dns.tf, modules/networking/variables.tf
https://github.com/chainguard-dev/infosec/issues/622
I created a new variable for this, `hosted_zone_logging_enabled`, that defaults to `true`. Consumers can easily disable this logging by setting the variable to `false`.
=> Add in DNS logging

modules/gke/README.md, modules/gke/main.tf, modules/gke/variables.tf
This PR adds opt-in datapath observability (for Dataplane v2) to the GKE module.
More info can be found in the GKE docs [here](https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability#standard-cluster-with-metrics-enabled).
=> Add dynamic block for advanced_datapath_observability_config to GKE module

pkg/workqueue/log.go
This implements the interface introduced in https://github.com/chainguard-dev/mono/blob/c41a30a7146aad0fdd12a4897b6da9267f180c74/api-internal/pkg/interceptors/requests.go#L22-L24.
This will not automatically cause these to be added to logs. Only in services that actually use the request handlers (which currently is only catalog-syncer) will call this.
=> workqueue: Implement logging interface for gRPC request handler

pkg/httpmetrics/metrics.go, pkg/httpmetrics/metrics_test.go, pkg/httpmetrics/transport.go
There are a few occurrences where we directly use `slog` instead of using our `clog` infrastructure.
=> Use clog logging consistently instead of slog

modules/cron/otel-config/config.yaml, modules/regional-service/otel-config/config.yaml
This has the potential of blowing up our metrics volume by quite a bit but is also the fix for all the duplicate timeseries warnings that we have, I think.
They look like this
```
rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: timeSeries[0-29] (example metric.type="prometheus.googleapis.com/grpc_client_handling_seconds/histogram", metric.labels={"service_name": "cve-remediation", "grpc_method": "GetPackageVersionMetadata", "team": "acceleration", "otel_scope_version": "0.130.0-dev", "otel_scope_name": "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver", "grpc_service": "chainguard.datastore.registry.Registry", "grpc_type": "unary"}): write for resource=prometheus_target{namespace:,instance:localhost:2112,job:cve-rem …
```
=> Fix service_instance_id attribute to pick up correct value

modules/dashboard/sections/http/main.tf
Currently, we're not filtering the request count metric by revision, causing the dashboard to say "Unspecified resource" and the graph to be wildly wrong. This fixes this oversight.
=> dashboard: Filter HTTP request count metric by revision

pkg/httpmetrics/transport.go
Instead of flooding the logs with all the hosts that aren't matching, this logs a warning about buckets not being setup once and then always returns "other".
=> httpmetrics: Warn once if buckets are not setup

modules/alerting/main.tf
include team filter in display name to differentiate
=> fix workqueue naming

modules/gke/main.tf, modules/gke/variables.tf
For existing clusters that are using older versions of the module, these settings did not exist, and if we upgrade, it tries to replace the node pools, but at this point, we want to have a minimum disruptive change, so if the setting is not set, it will keep the old behavior.
=> dynamic create the advanced_machine_features otherwise dont

pkg/workqueue/gcs/gcs.go, pkg/workqueue/gcs/metrics.go, pkg/workqueue/gcs/metrics_test.go
This will help us separate out metrics between priorities.
Used "${priority/100}xx" in order to be flexible here, but clients share responsibility here in choosing reasonable ranges. We can scope/cap this later if necessary.
=> workqueue: Add priority class to latency metrics

modules/cloudsql-postgres/README.md, modules/cloudsql-postgres/main.tf, modules/cloudsql-postgres/outputs.tf, modules/cloudsql-postgres/variables.tf
Add PSC configuration to the Cloud SQL Postgres module to enable secure cross-project connectivity. This allows consumer projects to connect to Cloud SQL instances in producer projects without VPC peering or Shared VPC.
to be used for https://github.com/chainguard-dev/internal-dev/issues/17448
=> cloudsql-postgres: add Private Service Connect (PSC) support for cross-project access

modules/secret/main.tf
The `placeholder` secret version is meant to assist with bootstrapping. However, due to the `prevent_destroy` block, callers can't drop the `create_placeholder_version` input var once the secret has been populated with a legitimate value. To allow callers to simplify their module configurations after bootstrap, drop the `lifecycle` block from this secret version.
=> secret: remove the lifecycle prevent destroy block from placeholder secret version

modules/cloudevents-workqueue/main.tf
Otherwise the trigger looks up the service before it's created.
=> Add a missing `depend_on`

modules/cloudevent-broker/README.md, modules/cloudevent-broker/ingress.tf, modules/cloudevent-broker/variables.tf, modules/regional-go-reconciler/README.md, modules/regional-go-reconciler/main.tf, modules/regional-go-reconciler/variables.tf, modules/workqueue/README.md, modules/workqueue/dispatcher.tf, modules/workqueue/main.tf, modules/workqueue/receiver.tf, modules/workqueue/variables.tf
`cpu_idle = false` means instance-based billing, which is cheaper for us for some services in some regions.
- Part of https://github.com/chainguard-dev/internal-dev/issues/20110
- Related to https://github.com/chainguard-dev/mono/pull/27115
I've tested this in my dev environment.
=> feat: cpu_idle for ingress, workqueue, reconciler

modules/dashboard/reconciler/README.md, modules/dashboard/reconciler/dashboard.tf
Reconcilers don't only do gRPC based traffic, but they'll also use HTTP clients etc. This shows them in the dashboard.
=> reconciler: Add HTTP section to dashboard
